# Generated by Django 6.0.3 on 2026-03-15 17:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo_url', models.URLField(blank=True, null=True)),
                ('source_url', models.URLField(db_index=True, unique=True)),
                ('source_platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('youthall', 'Youthall'), ('anbea', 'Anbea Kampüs'), ('boomerang', 'Boomerang'), ('toptalent', 'TopTalent'), ('savunma', 'Savunma Kariyer')], max_length=20)),
                ('em_focus_area', models.CharField(choices=[('imalat_metal_makine', 'İmalat, Metal ve Makine'), ('otomotiv_yan_sanayi', 'Otomotiv ve Yan Sanayi'), ('yazilim_bilisim_teknoloji', 'Yazılım, Bilişim ve Teknoloji'), ('hizmet_finans_danismanlik', 'Hizmet, Finans ve Danışmanlık'), ('eticaret_perakende_fmcg', 'E-Ticaret, Perakende ve FMCG'), ('savunma_havacilik_enerji', 'Savunma, Havacılık ve Enerji'), ('gida_kimya_saglik', 'Gıda, Kimya ve Sağlık'), ('lojistik_tasimacilık', 'Lojistik ve Taşımacılık'), ('tekstil_moda', 'Tekstil ve Moda'), ('insaat_yapi_malzemeleri', 'İnşaat ve Yapı Malzemeleri'), ('diger', 'Diğer')], default='diger', max_length=30)),
                ('internship_type', models.CharField(choices=[('zorunlu', 'Zorunlu Staj'), ('gonullu', 'Gönüllü Staj'), ('belirsiz', 'Belirsiz')], default='belirsiz', max_length=10)),
                ('company_origin', models.CharField(choices=[('yerli', 'Yerli'), ('yabanci', 'Yabancı'), ('belirsiz', 'Belirsiz')], default='belirsiz', max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('deadline_status', models.CharField(choices=[('urgent', 'Acil (≤7 gün)'), ('normal', 'Normal'), ('unknown', 'Tarih Belirtilmemiş'), ('upcoming', 'Yakında Açılacak'), ('expired', 'Süresi Dolmuş')], default='unknown', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_talent_program', models.BooleanField(db_index=True, default=False)),
                ('program_type', models.CharField(blank=True, choices=[('yaz_staj_programi', 'Yaz Staj Programı'), ('kariyer_baslangic', 'Kariyer Başlangıç Programı'), ('rotasyon', 'Rotasyon Programı'), ('graduate_program', 'Graduate Program'), ('akademi_bootcamp', 'Akademi / Bootcamp')], max_length=20, null=True)),
                ('duration_weeks', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScraperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider_name', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('new_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Scraper Logu',
                'verbose_name_plural': 'Scraper Logları',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('iuc_email', models.EmailField(max_length=254, unique=True)),
                ('department_year', models.IntegerField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('cv_url', models.URLField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Kaydedilen İlan',
                'verbose_name_plural': 'Kaydedilen İlanlar',
                'ordering': ['-bookmarked_at'],
                'unique_together': {('student', 'listing')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('internship_year', models.IntegerField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Değerlendirme',
                'verbose_name_plural': 'Değerlendirmeler',
                'ordering': ['-created_at'],
                'unique_together': {('listing', 'student')},
            },
        ),
    ]
