# Generated by Django 5.0.14 on 2026-03-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_sector_confidence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source_platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('kariyer', 'Kariyer.net'), ('youthall', 'Youthall'), ('anbea', 'Anbea Kampüs'), ('boomerang', 'Boomerang'), ('toptalent', 'TopTalent'), ('savunma', 'Savunma Kariyer'), ('odtu_kpm', 'ODTU KPM'), ('bogazici_km', 'Bogazici Kariyer'), ('ytu_orkam', 'YTU ORKAM'), ('itu_kariyer', 'ITU Kariyer')], max_length=20),
        ),
    ]
