# Generated by Django 5.0.14 on 2026-04-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_moderation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegativeKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Negatif Anahtar Kelime',
                'verbose_name_plural': 'Negatif Anahtar Kelimeler',
                'ordering': ['keyword'],
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Başvuru', 'verbose_name_plural': 'Başvurular'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Degerlendirme', 'verbose_name_plural': 'Degerlendirmeler'},
        ),
        migrations.AlterModelOptions(
            name='scraperlog',
            options={'ordering': ['-started_at'], 'verbose_name': 'Scraper Logu', 'verbose_name_plural': 'Scraper Loglari'},
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_origin',
            field=models.CharField(choices=[('yerli', 'Yerli'), ('yabanci', 'Yabanci'), ('belirsiz', 'Belirsiz')], default='belirsiz', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='deadline_status',
            field=models.CharField(choices=[('urgent', 'Acil (<=7 gun)'), ('normal', 'Normal'), ('unknown', 'Tarih Belirtilmemis'), ('upcoming', 'Yakinda Acilacak'), ('expired', 'Suresi Dolmus')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='em_focus_area',
            field=models.CharField(choices=[('imalat_metal_makine', 'Imalat, Metal ve Makine'), ('otomotiv_yan_sanayi', 'Otomotiv ve Yan Sanayi'), ('yazilim_bilisim_teknoloji', 'Yazilim, Bilisim ve Teknoloji'), ('hizmet_finans_danismanlik', 'Hizmet, Finans ve Danismanlik'), ('eticaret_perakende_fmcg', 'E-Ticaret, Perakende ve FMCG'), ('savunma_havacilik_enerji', 'Savunma, Havacilik ve Enerji'), ('gida_kimya_saglik', 'Gida, Kimya ve Saglik'), ('lojistik_tasimacilik', 'Lojistik ve Tasimacilik'), ('tekstil_moda', 'Tekstil ve Moda'), ('insaat_yapi_malzemeleri', 'Insaat ve Yapi Malzemeleri'), ('diger', 'Diger')], default='diger', max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='internship_type',
            field=models.CharField(choices=[('zorunlu', 'Zorunlu Staj'), ('gonullu', 'Gonullu Staj'), ('belirsiz', 'Belirsiz')], default='belirsiz', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='program_type',
            field=models.CharField(blank=True, choices=[('yaz_staj_programi', 'Yaz Staj Programi'), ('kariyer_baslangic', 'Kariyer Baslangic Programi'), ('rotasyon', 'Rotasyon Programi'), ('graduate_program', 'Graduate Program'), ('akademi_bootcamp', 'Akademi / Bootcamp')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='secondary_em_focus_area',
            field=models.CharField(blank=True, choices=[('imalat_metal_makine', 'Imalat, Metal ve Makine'), ('otomotiv_yan_sanayi', 'Otomotiv ve Yan Sanayi'), ('yazilim_bilisim_teknoloji', 'Yazilim, Bilisim ve Teknoloji'), ('hizmet_finans_danismanlik', 'Hizmet, Finans ve Danismanlik'), ('eticaret_perakende_fmcg', 'E-Ticaret, Perakende ve FMCG'), ('savunma_havacilik_enerji', 'Savunma, Havacilik ve Enerji'), ('gida_kimya_saglik', 'Gida, Kimya ve Saglik'), ('lojistik_tasimacilik', 'Lojistik ve Tasimacilik'), ('tekstil_moda', 'Tekstil ve Moda'), ('insaat_yapi_malzemeleri', 'Insaat ve Yapi Malzemeleri'), ('diger', 'Diger')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source_platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('kariyer', 'Kariyer.net'), ('youthall', 'Youthall'), ('anbea', 'Anbea Kampus'), ('boomerang', 'Boomerang'), ('toptalent', 'TopTalent'), ('savunma', 'Savunma Kariyer'), ('odtu_kpm', 'ODTU KPM'), ('bogazici_km', 'Bogazici Kariyer'), ('ytu_orkam', 'YTU ORKAM'), ('itu_kariyer', 'ITU Kariyer')], max_length=20),
        ),
    ]
