# Generated by Django 5.0.14 on 2026-04-04 15:27

from django.db import migrations


INITIAL_KEYWORDS = [
    'avukat', 'hukuk', 'savcı', 'noter', 'icra',
    'legal intern', 'certified legal intern', 'legal internship',
    'eczacı', 'eczane', 'eczacılık',
    'diş hekimi', 'dişçi', 'diş kliniği',
    'veteriner',
    'kuaför', 'berber', 'güzellik salonu',
    'aşçı', 'aşçıbaşı', 'pastane',
    'muhasebe', 'mali müşavir', 'serbest muhasebeci',
    'hemşire', 'hemşirelik', 'ebe', 'ebelik',
    'odyolog', 'fizyoterapist', 'diyetisyen',
    'psikolog', 'pedagog',
    'sosyal hizmet',
    'gazetecilik', 'muhabir',
    'iletişim fakültesi', 'iletisim fakultesi',
    'halkla ilişkiler', 'public relations',
    'backend developer', 'frontend developer', 'front-end developer',
    'front end developer', 'react developer', 'next.js developer',
    'nextjs developer', 'react/next.js developer', 'react nextjs developer',
    'javascript developer', 'node.js developer', 'nodejs developer',
    'full stack developer', 'full-stack developer',
    'fullstack developer', 'software developer', 'software engineer',
    'web developer', 'mobile developer', 'ios developer', 'android developer',
    'devops engineer', 'cloud engineer', 'site reliability',
    'qa engineer', 'test engineer',
    'ui developer', 'ux designer',
    'tasarım asistanı', 'stajyer tasarım asistanı',
    'design assistant', 'graphic designer', 'grafik tasarım',
    'insansız hava araçları alt sistemleri proje mühendisi',
    'üretim operatörü', 'uretim operatoru',
    'satış uzmanı', 'satis uzmani', 'satış operasyonları uzmanı',
    'halkla ilişkiler stajeri', 'halkla iliskiler stajeri',
    'pazarlama ve halkla ilişkiler stajyeri', 'public relations intern',
    'supervisor', 'country operations', 'operations manager',
    'minimum 5 years', 'minimum 6 years', 'minimum 7 years',
    'at least 5 years', 'at least 6 years', 'at least 7 years',
    '5+ years', '6+ years', '7+ years',
    '5 years experience', '6 years experience', '7 years experience',
    'cyber security', 'siber güvenlik',
    'network engineer', 'ağ uzmanı',
    'database administrator',
    'game developer', 'oyun geliştirici',
    'yazılım geliştirme', 'yazılım test', 'yazılım mühendis',
    'yazılım stajyer', 'test stajyer',
    'bilgisayar mühendis', 'elektronik mühendis',
    'sistem yönetici', 'system admin',
]


def seed_keywords(apps, schema_editor):
    NegativeKeyword = apps.get_model('listings', 'NegativeKeyword')
    for kw in INITIAL_KEYWORDS:
        NegativeKeyword.objects.get_or_create(keyword=kw)


def unseed_keywords(apps, schema_editor):
    NegativeKeyword = apps.get_model('listings', 'NegativeKeyword')
    NegativeKeyword.objects.filter(keyword__in=INITIAL_KEYWORDS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_add_negative_keyword_model'),
    ]

    operations = [
        migrations.RunPython(seed_keywords, unseed_keywords),
    ]
