# Generated by Django 5.0.14 on 2026-04-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_seed_negative_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppressedListingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(db_index=True, unique=True)),
                ('source_platform', models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('kariyer', 'Kariyer.net'), ('youthall', 'Youthall'), ('anbea', 'Anbea Kampus'), ('boomerang', 'Boomerang'), ('toptalent', 'TopTalent'), ('savunma', 'Savunma Kariyer'), ('odtu_kpm', 'ODTU KPM'), ('bogazici_km', 'Bogazici Kariyer'), ('ytu_orkam', 'YTU ORKAM'), ('itu_kariyer', 'ITU Kariyer')], default='', max_length=20)),
                ('listing_title', models.CharField(blank=True, default='', max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('suppressed_reason', models.CharField(default='manual_delete', max_length=50)),
                ('suppressed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Engellenen İlan Kaynağı',
                'verbose_name_plural': 'Engellenen İlan Kaynakları',
                'ordering': ['-suppressed_at'],
            },
        ),
    ]
