# Generated by Django 5.0.14 on 2026-04-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_suppressed_listing_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='application_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source_url',
            field=models.URLField(db_index=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cv_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='suppressedlistingsource',
            name='source_url',
            field=models.URLField(db_index=True, max_length=500, unique=True),
        ),
    ]
