# Generated by Django 5.0.14 on 2026-04-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_expand_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='homepage_featured_image_url',
            field=models.URLField(blank=True, default='', help_text='Kartin ust banner gorseli icin harici gorsel URLsi.', max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='homepage_featured_rank',
            field=models.PositiveSmallIntegerField(default=99, help_text='Kucuk sayi once gelir. Ana sayfada en fazla 3 ilan gosterilir.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='homepage_featured_summary',
            field=models.TextField(blank=True, default='', help_text='Kartta kullanilacak kisa ozet. Bos birakilirsa ilan aciklamasindan otomatik uretilir.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_homepage_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Ana sayfadaki "One Cikan Ilanlar" bolumunde goster.'),
        ),
    ]
