# Generated by Django 5.0.14 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_listing_homepage_featured_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='source_platform',
            field=models.CharField(
                choices=[
                    ('linkedin', 'LinkedIn'),
                    ('kariyer', 'Kariyer.net'),
                    ('youthall', 'Youthall'),
                    ('anbea', 'Anbea Kampus'),
                    ('boomerang', 'Boomerang'),
                    ('toptalent', 'TopTalent'),
                    ('savunma', 'Savunma Kariyer'),
                    ('odtu_kpm', 'ODTU KPM'),
                    ('bogazici_km', 'Bogazici Kariyer'),
                    ('ytu_orkam', 'YTU ORKAM'),
                    ('itu_kariyer', 'ITU Kariyer'),
                    ('pythiango', 'PythianGo'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='suppressedlistingsource',
            name='source_platform',
            field=models.CharField(
                blank=True,
                choices=[
                    ('linkedin', 'LinkedIn'),
                    ('kariyer', 'Kariyer.net'),
                    ('youthall', 'Youthall'),
                    ('anbea', 'Anbea Kampus'),
                    ('boomerang', 'Boomerang'),
                    ('toptalent', 'TopTalent'),
                    ('savunma', 'Savunma Kariyer'),
                    ('odtu_kpm', 'ODTU KPM'),
                    ('bogazici_km', 'Bogazici Kariyer'),
                    ('ytu_orkam', 'YTU ORKAM'),
                    ('itu_kariyer', 'ITU Kariyer'),
                    ('pythiango', 'PythianGo'),
                ],
                default='',
                max_length=20,
            ),
        ),
    ]
