# Generated by Django 5.0.14 on 2026-04-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_add_pythiango_source_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalcomment',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='journalcomment',
            name='student',
        ),
        migrations.DeleteModel(
            name='InternshipJournal',
        ),
        migrations.DeleteModel(
            name='JournalComment',
        ),
    ]
