# Generated by Django 5.0.14 on 2026-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_remove_journalcomment_journal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='source_platform',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='suppressedlistingsource',
            name='source_platform',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
    ]
