# Generated by Django 5.0.14 on 2026-04-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_listing_source_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='average_rating',
            field=models.FloatField(db_index=True, default=0.0, help_text='Denormalize: Ortalama puan. Review sinyalleriyle güncellenir.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bookmark_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Denormalize: Bookmark sayısı. post_save/post_delete sinyalleriyle güncellenir.'),
        ),
    ]
