# Generated by Django 5.0.14 on 2026-05-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_trigram_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('result_count', models.IntegerField()),
                ('filters_applied', models.JSONField(default=dict)),
                ('has_results', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arama Logu',
                'verbose_name_plural': 'Arama Loglari',
                'ordering': ['-created_at'],
            },
        ),
    ]
