# Generated by Django 5.1.15 on 2026-05-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_listing_trigram_gin_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-quality_score', '-created_at'], 'verbose_name': 'İlan', 'verbose_name_plural': 'İlanlar'},
        ),
        migrations.AddField(
            model_name='listing',
            name='quality_score',
            field=models.SmallIntegerField(db_index=True, default=0, help_text='0-100 arası kalite skoru. (Açıklama uzunluğu, deadline vb. metriklerle)'),
        ),
    ]
