# Generated by Django 5.1.15 on 2026-05-02 15:56

from django.db import migrations

def compute_quality_scores(apps, schema_editor):
    Listing = apps.get_model('listings', 'Listing')
    listings_to_update = []
    
    for listing in Listing.objects.all():
        score = 0
        if listing.description and len(listing.description) > 200:
            score += 20
        if listing.requirements and len(listing.requirements.strip()) > 0:
            score += 20
        if listing.application_deadline:
            score += 20
        if listing.duration_weeks:
            score += 15
        if listing.company_logo_url:
            score += 15
        if listing.application_url:
            score += 10
            
        listing.quality_score = min(score, 100)
        listings_to_update.append(listing)
        
        if len(listings_to_update) >= 500:
            Listing.objects.bulk_update(listings_to_update, ['quality_score'])
            listings_to_update = []
            
    if listings_to_update:
        Listing.objects.bulk_update(listings_to_update, ['quality_score'])

class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_alter_listing_options_listing_quality_score'),
    ]

    operations = [
        migrations.RunPython(compute_quality_scores, reverse_code=migrations.RunPython.noop),
    ]
