# Generated by Django 5.1.15 on 2026-05-02 16:11

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_populate_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='listings_li_search__219da8_gin'),
        ),
    ]
