# Generated by Django 5.1.15 on 2026-05-02 16:11

from django.db import migrations

def compute_search_vector(apps, schema_editor):
    Listing = apps.get_model('listings', 'Listing')
    if schema_editor.connection.vendor == 'postgresql':
        from django.contrib.postgres.search import SearchVector
        Listing.objects.update(
            search_vector=(
                SearchVector('title', weight='A') +
                SearchVector('company_name', weight='A') +
                SearchVector('location', weight='B') +
                SearchVector('description', weight='C') +
                SearchVector('requirements', weight='C')
            )
        )

class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_listing_search_vector_and_more'),
    ]

    operations = [
        migrations.RunPython(compute_search_vector, reverse_code=migrations.RunPython.noop),
    ]
