KNOWN_DOMAINS: dict[str, str] = {
    # Tech / Social Media
    'tiktok': 'tiktok.com',
    'google': 'google.com',
    'microsoft': 'microsoft.com',
    'meta': 'meta.com',
    'apple': 'apple.com',
    'amazon': 'amazon.com.tr',
    'huawei': 'huawei.com',
    'samsung': 'samsung.com',
    'nvidia': 'nvidia.com',
    'oracle': 'oracle.com',
    'sap': 'sap.com',
    'ibm': 'ibm.com',
    'cisco': 'cisco.com',
    'adobe': 'adobe.com',
    'spotify': 'spotify.com',
    'trendyol': 'trendyol.com',
    'hepsiburada': 'hepsiburada.com',
    'getir': 'getir.com',
    'n11': 'n11.com',
    'sahibinden': 'sahibinden.com',
    'yemeksepeti': 'yemeksepeti.com',
    # Telco
    'turkcell': 'turkcell.com.tr',
    'türk telekom': 'turktelekom.com.tr',
    'vodafone': 'vodafone.com.tr',
    # Automotive
    'mercedes-benz': 'mercedes-benz.com.tr',
    'mercedes': 'mercedes-benz.com.tr',
    'ford': 'ford.com.tr',
    'toyota': 'toyota.com.tr',
    'bmw': 'bmw.com.tr',
    'volkswagen': 'volkswagen.com.tr',
    'hyundai': 'hyundai.com.tr',
    'renault': 'renault.com.tr',
    'fiat': 'fiat.com.tr',
    'honda': 'honda.com.tr',
    'tofaş': 'tofas.com.tr',
    # Industry / Manufacturing
    'bosch': 'bosch.com.tr',
    'siemens': 'siemens.com.tr',
    'arçelik': 'arcelik.com.tr',
    'vestel': 'vestel.com.tr',
    'schneider': 'se.com',
    'abb': 'abb.com',
    # Holdings
    'koç': 'koc.com.tr',
    'sabancı': 'sabanci.com',
    'doğuş': 'dogus.com.tr',
    'zorlu': 'zorlu.com',
    # Defence / Aerospace
    'aselsan': 'aselsan.com.tr',
    'havelsan': 'havelsan.com.tr',
    'tusaş': 'tusas.com',
    'roketsan': 'roketsan.com.tr',
    'baykar': 'baykartech.com',
    # Banking / Finance
    'akbank': 'akbank.com',
    'garanti': 'garantibbva.com.tr',
    'yapı kredi': 'yapikredi.com.tr',
    'iş bankası': 'isbank.com.tr',
    'ziraat': 'ziraatbank.com.tr',
    'halkbank': 'halkbank.com.tr',
    'qnb finansbank': 'qnb.com.tr',
    'denizbank': 'denizbank.com',
    'vakıfbank': 'vakifbank.com.tr',
    # Energy
    'tüpraş': 'tupras.com.tr',
    'petkim': 'petkim.com.tr',
    'enerjisa': 'enerjisa.com.tr',
    'socar': 'socar.com.tr',
    # FMCG / Food
    'unilever': 'unilever.com.tr',
    'nestlé': 'nestle.com.tr',
    'nestle': 'nestle.com.tr',
    'coca-cola': 'coca-cola.com.tr',
    'pepsi': 'pepsico.com.tr',
    'ülker': 'ulker.com.tr',
    # Airlines
    'thy': 'turkishairlines.com',
    'türk hava yolları': 'turkishairlines.com',
    'pegasus': 'flypgs.com',
    # Pharma / Health
    'bayer': 'bayer.com.tr',
    'roche': 'roche.com.tr',
    'novartis': 'novartis.com.tr',
    'pfizer': 'pfizer.com.tr',
    'abdi ibrahim': 'abdiibrahim.com.tr',
    # Consulting
    'deloitte': 'deloitte.com',
    'pwc': 'pwc.com.tr',
    'kpmg': 'kpmg.com.tr',
    'ey': 'ey.com',
    # Retail
    'lc waikiki': 'lcwaikiki.com',
    'lcw': 'lcwaikiki.com',
    'watsons': 'watsons.com.tr',
    'beymen': 'beymen.com',
    'defacto': 'defacto.com.tr',
    'koton': 'koton.com',
    'mavi': 'mavi.com',
    'migros': 'migros.com.tr',
    # Misc
    'commencis': 'commencis.com',
    'sestek': 'sestek.com',
    'phinia': 'phinia.com',
    'kızılay': 'kizilay.org.tr',
    'kızılay teknoloji': 'kizilaykariyer.com',
    'coral travel': 'coraltravel.com.tr',
}
